#!/usr/bin/env php
<?php

require_once __DIR__."/vendor/autoload.php";

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| First we need to get an application instance. This creates an instance
| of the application / container and bootstraps the application so it
| is ready to receive HTTP / Console requests from the environment.
|
*/


/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/
$app = new Artisan\Stub\Application;
$app->singleton(
    'Illuminate\Contracts\Debug\ExceptionHandler',
    'Artisan\Exceptions\Handler'
);

$kernel = new Artisan\Console\Kernel(
    $app,
    new Artisan\Stub\Dispatcher()
);

exit($kernel->handle(new ArgvInput, new ConsoleOutput));
